services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:  goes_template 
    ports:
      - "5432:5432"
    volumes:
      - goes_template_postgres_data:/var/lib/postgresql/data

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    container_name: goes_template-openobserve
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "helloworld"
    ports:
      - "5080:5080"
    volumes:
      - goes_template_openobserve_data:/data

volumes:
  goes_template_postgres_data:
  goes_template_openobserve_data:
