services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: helloworld
    ports:
      - "27017:27017"
    volumes:
      - scalar_healer_mongo_data:/data/db

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    container_name: scalar_healer_openobserve
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "helloworld"
    ports:
      - "5080:5080"
    volumes:
      - scalar_healer_openobserve_data:/data

volumes:
  scalar_healer_mongo_data:
  scalar_healer_openobserve_data:
