services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: ${HEALER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HEALER_POSTGRES_PASSWORD}
      POSTGRES_DB:  ${HEALER_POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - scalar_healer_data:/var/lib/postgresql/data
 
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    container_name: scalar_healer_openobserve
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "helloworld"
    ports:
      - "5080:5080"
    volumes:
      - scalar_healer_openobserve_data:/data

volumes:
  scalar_healer_data:
  scalar_healer_openobserve_data:
