// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chain_redeem_sessions.sql

package sqlc

import (
	"context"
)

const saveChainRedeemSessions = `-- name: SaveChainRedeemSessions :exec
INSERT INTO chain_redeem_sessions (chain, custodian_group_uid, sequence, current_phase)
VALUES (unnest($1::text[]), unnest($2::bytea[]), unnest($3::bigint[]), unnest($4::text[])::redeem_phase)
ON CONFLICT (chain, custodian_group_uid) DO UPDATE
SET sequence = EXCLUDED.sequence, current_phase = EXCLUDED.current_phase
`

type SaveChainRedeemSessionsParams struct {
	Column1 []string `json:"column_1"`
	Column2 [][]byte `json:"column_2"`
	Column3 []int64  `json:"column_3"`
	Column4 []string `json:"column_4"`
}

func (q *Queries) SaveChainRedeemSessions(ctx context.Context, arg SaveChainRedeemSessionsParams) error {
	_, err := q.db.Exec(ctx, saveChainRedeemSessions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}
