// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package sqlc

import (
	"context"
)

const saveCommands = `-- name: SaveCommands :exec
INSERT INTO commands (command_id, chain, params, status, command_type)
VALUES (unnest($1::bytea[]), unnest($2::text[]), unnest($3::bytea[]), unnest($4::int[]), unnest($5::command_type[]))
`

type SaveCommandsParams struct {
	Column1 [][]byte      `json:"column_1"`
	Column2 []string      `json:"column_2"`
	Column3 [][]byte      `json:"column_3"`
	Column4 []int32       `json:"column_4"`
	Column5 []CommandType `json:"column_5"`
}

func (q *Queries) SaveCommands(ctx context.Context, arg SaveCommandsParams) error {
	_, err := q.db.Exec(ctx, saveCommands,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}
