// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BridgeRequest struct {
	ID        int64            `json:"id"`
	Address   []byte           `json:"address"`
	Signature []byte           `json:"signature"`
	ChainID   pgtype.Numeric   `json:"chain_id"`
	TxHash    []byte           `json:"tx_hash"`
	Nonce     pgtype.Numeric   `json:"nonce"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CustodianGroup struct {
	ID            int64            `json:"id"`
	Uid           []byte           `json:"uid"`
	Name          string           `json:"name"`
	BitcoinPubkey []byte           `json:"bitcoin_pubkey"`
	Quorum        int64            `json:"quorum"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type GatewayAddress struct {
	ID        int64            `json:"id"`
	Address   []byte           `json:"address"`
	ChainID   pgtype.Numeric   `json:"chain_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Nonce struct {
	ID        int64            `json:"id"`
	Address   []byte           `json:"address"`
	Nonce     pgtype.Numeric   `json:"nonce"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Protocol struct {
	ID                 int64            `json:"id"`
	Asset              string           `json:"asset"`
	Name               string           `json:"name"`
	CustodianGroupName string           `json:"custodian_group_name"`
	CustodianGroupUid  []byte           `json:"custodian_group_uid"`
	Tag                string           `json:"tag"`
	LiquidityModel     string           `json:"liquidity_model"`
	Symbol             string           `json:"symbol"`
	Decimals           int64            `json:"decimals"`
	Capacity           pgtype.Numeric   `json:"capacity"`
	DailyMintLimit     pgtype.Numeric   `json:"daily_mint_limit"`
	Avatar             string           `json:"avatar"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type RedeemRequest struct {
	ID        int64            `json:"id"`
	Address   []byte           `json:"address"`
	Signature []byte           `json:"signature"`
	ChainID   pgtype.Numeric   `json:"chain_id"`
	Symbol    string           `json:"symbol"`
	Amount    string           `json:"amount"`
	Nonce     pgtype.Numeric   `json:"nonce"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Reservation struct {
	ID        int64            `json:"id"`
	UtxoTxID  []byte           `json:"utxo_tx_id"`
	UtxoVout  int64            `json:"utxo_vout"`
	RequestID string           `json:"request_id"`
	Amount    pgtype.Numeric   `json:"amount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Token struct {
	ID        int64            `json:"id"`
	Protocol  string           `json:"protocol"`
	Symbol    string           `json:"symbol"`
	ChainID   pgtype.Numeric   `json:"chain_id"`
	Active    bool             `json:"active"`
	Address   []byte           `json:"address"`
	Decimal   pgtype.Numeric   `json:"decimal"`
	Name      string           `json:"name"`
	Avatar    string           `json:"avatar"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type TransferRequest struct {
	ID                 int64            `json:"id"`
	Address            []byte           `json:"address"`
	Signature          []byte           `json:"signature"`
	ChainID            pgtype.Numeric   `json:"chain_id"`
	DestinationChain   string           `json:"destination_chain"`
	DestinationAddress []byte           `json:"destination_address"`
	Symbol             string           `json:"symbol"`
	Amount             string           `json:"amount"`
	Nonce              pgtype.Numeric   `json:"nonce"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type Utxo struct {
	ID                int64            `json:"id"`
	TxID              []byte           `json:"tx_id"`
	Vout              int64            `json:"vout"`
	ScriptPubkey      []byte           `json:"script_pubkey"`
	AmountInSats      pgtype.Numeric   `json:"amount_in_sats"`
	CustodianGroupUid []byte           `json:"custodian_group_uid"`
	BlockHeight       int64            `json:"block_height"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}
