// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: protocols.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProtocol = `-- name: GetProtocol :many
SELECT
    p.id, p.symbol, p.name, p.bitcoin_pubkey, p.decimals, p.avatar, p.custodian_group_name, p.custodian_group_uid, p.tag, p.liquidity_model, p.capacity, p.daily_mint_limit, p.created_at, p.updated_at,
    cg.custodians,
    cg.quorum,
    t.chain,
    t.chain_id,
    t.address
FROM protocols p
JOIN custodian_groups cg ON cg.uid = p.custodian_group_uid
LEFT JOIN tokens t ON t.symbol = p.symbol
WHERE p.symbol = $1
GROUP BY 
    p.id,
    p.symbol,
    p.name,
    p.bitcoin_pubkey,
    p.custodian_group_name,
    p.custodian_group_uid,
    cg.custodians,
    cg.quorum,
    p.tag,
    p.decimals, 
    p.liquidity_model,
    p.avatar,
    p.capacity,
    p.daily_mint_limit,
    p.created_at,
    p.updated_at,
    t.chain,
    t.chain_id,
    t.address
`

type GetProtocolRow struct {
	ID                 int64            `json:"id"`
	Symbol             string           `json:"symbol"`
	Name               string           `json:"name"`
	BitcoinPubkey      []byte           `json:"bitcoin_pubkey"`
	Decimals           int64            `json:"decimals"`
	Avatar             string           `json:"avatar"`
	CustodianGroupName string           `json:"custodian_group_name"`
	CustodianGroupUid  []byte           `json:"custodian_group_uid"`
	Tag                string           `json:"tag"`
	LiquidityModel     string           `json:"liquidity_model"`
	Capacity           pgtype.Numeric   `json:"capacity"`
	DailyMintLimit     pgtype.Numeric   `json:"daily_mint_limit"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Custodians         []byte           `json:"custodians"`
	Quorum             int64            `json:"quorum"`
	Chain              pgtype.Text      `json:"chain"`
	ChainID            pgtype.Numeric   `json:"chain_id"`
	Address            []byte           `json:"address"`
}

func (q *Queries) GetProtocol(ctx context.Context, symbol string) ([]GetProtocolRow, error) {
	rows, err := q.db.Query(ctx, getProtocol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProtocolRow{}
	for rows.Next() {
		var i GetProtocolRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.BitcoinPubkey,
			&i.Decimals,
			&i.Avatar,
			&i.CustodianGroupName,
			&i.CustodianGroupUid,
			&i.Tag,
			&i.LiquidityModel,
			&i.Capacity,
			&i.DailyMintLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Custodians,
			&i.Quorum,
			&i.Chain,
			&i.ChainID,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProtocols = `-- name: GetProtocols :many
SELECT
    p.id, p.symbol, p.name, p.bitcoin_pubkey, p.decimals, p.avatar, p.custodian_group_name, p.custodian_group_uid, p.tag, p.liquidity_model, p.capacity, p.daily_mint_limit, p.created_at, p.updated_at,
    cg.custodians,
    cg.quorum,
    t.chain,
    t.chain_id,
    t.address
FROM protocols p
JOIN custodian_groups cg ON cg.uid = p.custodian_group_uid
LEFT JOIN tokens t ON t.symbol = p.symbol
GROUP BY 
    p.id,
    p.symbol,
    p.name,
    p.bitcoin_pubkey,
    p.custodian_group_name,
    p.custodian_group_uid,
    cg.custodians,
    cg.quorum,
    p.tag,
    p.decimals, 
    p.liquidity_model,
    p.avatar,
    p.capacity,
    p.daily_mint_limit,
    p.created_at,
    p.updated_at,
    t.chain,
    t.chain_id,
    t.address
`

type GetProtocolsRow struct {
	ID                 int64            `json:"id"`
	Symbol             string           `json:"symbol"`
	Name               string           `json:"name"`
	BitcoinPubkey      []byte           `json:"bitcoin_pubkey"`
	Decimals           int64            `json:"decimals"`
	Avatar             string           `json:"avatar"`
	CustodianGroupName string           `json:"custodian_group_name"`
	CustodianGroupUid  []byte           `json:"custodian_group_uid"`
	Tag                string           `json:"tag"`
	LiquidityModel     string           `json:"liquidity_model"`
	Capacity           pgtype.Numeric   `json:"capacity"`
	DailyMintLimit     pgtype.Numeric   `json:"daily_mint_limit"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Custodians         []byte           `json:"custodians"`
	Quorum             int64            `json:"quorum"`
	Chain              pgtype.Text      `json:"chain"`
	ChainID            pgtype.Numeric   `json:"chain_id"`
	Address            []byte           `json:"address"`
}

func (q *Queries) GetProtocols(ctx context.Context) ([]GetProtocolsRow, error) {
	rows, err := q.db.Query(ctx, getProtocols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProtocolsRow{}
	for rows.Next() {
		var i GetProtocolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.BitcoinPubkey,
			&i.Decimals,
			&i.Avatar,
			&i.CustodianGroupName,
			&i.CustodianGroupUid,
			&i.Tag,
			&i.LiquidityModel,
			&i.Capacity,
			&i.DailyMintLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Custodians,
			&i.Quorum,
			&i.Chain,
			&i.ChainID,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveProtocols = `-- name: SaveProtocols :exec
INSERT INTO protocols (symbol, name, bitcoin_pubkey, custodian_group_name, custodian_group_uid, tag, liquidity_model, decimals, capacity, daily_mint_limit, avatar)
VALUES(unnest($1::text[]), unnest($2::text[]), unnest($3::bytea[]), unnest($4::text[]), unnest($5::bytea[]), unnest($6::text[]), unnest($7::text[]), unnest($8::bigint[]), unnest($9::numeric[]), unnest($10::numeric[]), unnest($11::text[])) ON CONFLICT DO NOTHING
`

type SaveProtocolsParams struct {
	Column1  []string         `json:"column_1"`
	Column2  []string         `json:"column_2"`
	Column3  [][]byte         `json:"column_3"`
	Column4  []string         `json:"column_4"`
	Column5  [][]byte         `json:"column_5"`
	Column6  []string         `json:"column_6"`
	Column7  []string         `json:"column_7"`
	Column8  []int64          `json:"column_8"`
	Column9  []pgtype.Numeric `json:"column_9"`
	Column10 []pgtype.Numeric `json:"column_10"`
	Column11 []string         `json:"column_11"`
}

func (q *Queries) SaveProtocols(ctx context.Context, arg SaveProtocolsParams) error {
	_, err := q.db.Exec(ctx, saveProtocols,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
	)
	return err
}
