// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGatewayAddress(ctx context.Context, arg CreateGatewayAddressParams) error
	CreateGatewayAddresses(ctx context.Context, arg CreateGatewayAddressesParams) error
	DeleteReservations(ctx context.Context) error
	DeleteUTXOs(ctx context.Context, dollar_1 []byte) error
	GetAllCustodianGroups(ctx context.Context) ([]CustodianGroup, error)
	GetChainRedeemSession(ctx context.Context, arg GetChainRedeemSessionParams) (ChainRedeemSession, error)
	GetCommandBatchByID(ctx context.Context, id []byte) (CommandBatch, error)
	GetCommandBatches(ctx context.Context) ([]CommandBatch, error)
	GetCompletedRedeemSessions(ctx context.Context) ([]RedeemSession, error)
	GetCustodianGroupByUID(ctx context.Context, uid []byte) (CustodianGroup, error)
	GetGatewayAddress(ctx context.Context, chain string) ([]byte, error)
	GetNonce(ctx context.Context, address []byte) (pgtype.Numeric, error)
	GetProtocol(ctx context.Context, symbol string) ([]GetProtocolRow, error)
	GetProtocols(ctx context.Context) ([]GetProtocolsRow, error)
	GetRedeemSession(ctx context.Context, custodianGroupUid []byte) (RedeemSession, error)
	GetTokenAddressBySymbol(ctx context.Context, arg GetTokenAddressBySymbolParams) ([]byte, error)
	GetTokenSymbolByAddress(ctx context.Context, arg GetTokenSymbolByAddressParams) (string, error)
	GetUTXOs(ctx context.Context, arg GetUTXOsParams) ([]Utxo, error)
	GetUTXOsByCustodianGroupUID(ctx context.Context, dollar_1 []byte) ([]Utxo, error)
	GetUtxoSnapshot(ctx context.Context, dollar_1 []byte) ([]GetUtxoSnapshotRow, error)
	ListBridgeRequests(ctx context.Context, arg ListBridgeRequestsParams) ([]BridgeRequest, error)
	ListPendingSigningRedeemCommands(ctx context.Context) ([]RedeemCommand, error)
	ListRedeemRequests(ctx context.Context, arg ListRedeemRequestsParams) ([]ListRedeemRequestsRow, error)
	ListTokens(ctx context.Context) ([]Token, error)
	ListTransferRequests(ctx context.Context, arg ListTransferRequestsParams) ([]TransferRequest, error)
	SaveBridgeRequest(ctx context.Context, arg SaveBridgeRequestParams) error
	SaveChainRedeemSessions(ctx context.Context, arg SaveChainRedeemSessionsParams) error
	SaveCommandBatches(ctx context.Context, arg SaveCommandBatchesParams) error
	SaveCommands(ctx context.Context, arg SaveCommandsParams) error
	SaveCustodianGroups(ctx context.Context, arg SaveCustodianGroupsParams) error
	SaveProtocols(ctx context.Context, arg SaveProtocolsParams) error
	SaveRedeemCommand(ctx context.Context, arg SaveRedeemCommandParams) error
	SaveRedeemCommands(ctx context.Context, arg SaveRedeemCommandsParams) error
	SaveRedeemRequest(ctx context.Context, arg SaveRedeemRequestParams) error
	SaveRedeemSessions(ctx context.Context, arg SaveRedeemSessionsParams) error
	SaveReservations(ctx context.Context, dollar_1 [][]byte) ([][]byte, error)
	SaveTokens(ctx context.Context, arg SaveTokensParams) error
	SaveTransferRequest(ctx context.Context, arg SaveTransferRequestParams) error
	SaveUTXOs(ctx context.Context, arg SaveUTXOsParams) error
	SaveUtxoReservations(ctx context.Context, arg SaveUtxoReservationsParams) error
	SubmitRedeemCommandSignature(ctx context.Context, arg SubmitRedeemCommandSignatureParams) error
	UpsertNonce(ctx context.Context, arg UpsertNonceParams) error
}

var _ Querier = (*Queries)(nil)
