// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGatewayAddress(ctx context.Context, arg CreateGatewayAddressParams) error
	GetGatewayAddress(ctx context.Context, chainID pgtype.Numeric) ([]byte, error)
	GetNonce(ctx context.Context, address []byte) (pgtype.Numeric, error)
	GetTokenAddressBySymbol(ctx context.Context, arg GetTokenAddressBySymbolParams) ([]byte, error)
	GetTokenSymbolByAddress(ctx context.Context, arg GetTokenSymbolByAddressParams) (string, error)
	ListBridgeRequests(ctx context.Context, arg ListBridgeRequestsParams) ([]BridgeRequest, error)
	ListRedeemRequests(ctx context.Context, arg ListRedeemRequestsParams) ([]RedeemRequest, error)
	ListTokens(ctx context.Context) ([]Token, error)
	ListTransferRequests(ctx context.Context, arg ListTransferRequestsParams) ([]TransferRequest, error)
	SaveBridgeRequest(ctx context.Context, arg SaveBridgeRequestParams) error
	SaveRedeemRequest(ctx context.Context, arg SaveRedeemRequestParams) error
	SaveTokens(ctx context.Context, arg SaveTokensParams) error
	SaveTransferRequest(ctx context.Context, arg SaveTransferRequestParams) error
	UpsertNonce(ctx context.Context, arg UpsertNonceParams) error
}

var _ Querier = (*Queries)(nil)
