// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: redeem_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRedeemRequests = `-- name: ListRedeemRequests :many
SELECT id, address, source_chain, dest_chain, symbol, amount, locking_script, created_at, updated_at, COUNT(*) OVER() AS count
FROM redeem_requests
WHERE address = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRedeemRequestsParams struct {
	Address []byte `json:"address"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListRedeemRequestsRow struct {
	ID            int64            `json:"id"`
	Address       []byte           `json:"address"`
	SourceChain   string           `json:"source_chain"`
	DestChain     string           `json:"dest_chain"`
	Symbol        string           `json:"symbol"`
	Amount        string           `json:"amount"`
	LockingScript []byte           `json:"locking_script"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Count         int64            `json:"count"`
}

func (q *Queries) ListRedeemRequests(ctx context.Context, arg ListRedeemRequestsParams) ([]ListRedeemRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRedeemRequests, arg.Address, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRedeemRequestsRow{}
	for rows.Next() {
		var i ListRedeemRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.SourceChain,
			&i.DestChain,
			&i.Symbol,
			&i.Amount,
			&i.LockingScript,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRedeemRequest = `-- name: SaveRedeemRequest :exec
INSERT INTO redeem_requests (address,  source_chain, dest_chain, symbol, amount, locking_script)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveRedeemRequestParams struct {
	Address       []byte `json:"address"`
	SourceChain   string `json:"source_chain"`
	DestChain     string `json:"dest_chain"`
	Symbol        string `json:"symbol"`
	Amount        string `json:"amount"`
	LockingScript []byte `json:"locking_script"`
}

func (q *Queries) SaveRedeemRequest(ctx context.Context, arg SaveRedeemRequestParams) error {
	_, err := q.db.Exec(ctx, saveRedeemRequest,
		arg.Address,
		arg.SourceChain,
		arg.DestChain,
		arg.Symbol,
		arg.Amount,
		arg.LockingScript,
	)
	return err
}
