// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReservations = `-- name: DeleteReservations :exec
DELETE FROM reservations WHERE id IN (
  SELECT r.id
  FROM reservations r
  LEFT JOIN utxo_reservations ur ON r.id = ur.reservation_id
  WHERE ur.reservation_id IS NULL
)
`

func (q *Queries) DeleteReservations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteReservations)
	return err
}

const saveReservations = `-- name: SaveReservations :exec
INSERT INTO reservations (
    utxo_tx_id,
    utxo_vout,
    request_id,
    amount
) VALUES (
    unnest($1::bytea[]),
    unnest($2::bigint[]),
    unnest($3::text[]),
    unnest($4::numeric[])
)
`

type SaveReservationsParams struct {
	Column1 [][]byte         `json:"column_1"`
	Column2 []int64          `json:"column_2"`
	Column3 []string         `json:"column_3"`
	Column4 []pgtype.Numeric `json:"column_4"`
}

func (q *Queries) SaveReservations(ctx context.Context, arg SaveReservationsParams) error {
	_, err := q.db.Exec(ctx, saveReservations,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}
