// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transfer_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTransferRequests = `-- name: ListTransferRequests :many
SELECT id, address, signature, chain_id, destination_chain, destination_address, symbol, amount, nonce, created_at, updated_at
FROM transfer_requests
WHERE address = $1
ORDER BY nonce DESC
LIMIT $2 OFFSET $3
`

type ListTransferRequestsParams struct {
	Address []byte `json:"address"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTransferRequests(ctx context.Context, arg ListTransferRequestsParams) ([]TransferRequest, error) {
	rows, err := q.db.Query(ctx, listTransferRequests, arg.Address, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferRequest{}
	for rows.Next() {
		var i TransferRequest
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Signature,
			&i.ChainID,
			&i.DestinationChain,
			&i.DestinationAddress,
			&i.Symbol,
			&i.Amount,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTransferRequest = `-- name: SaveTransferRequest :exec
INSERT INTO transfer_requests (address,  signature, chain_id, destination_chain, destination_address, symbol, amount, nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveTransferRequestParams struct {
	Address            []byte         `json:"address"`
	Signature          []byte         `json:"signature"`
	ChainID            pgtype.Numeric `json:"chain_id"`
	DestinationChain   string         `json:"destination_chain"`
	DestinationAddress []byte         `json:"destination_address"`
	Symbol             string         `json:"symbol"`
	Amount             string         `json:"amount"`
	Nonce              pgtype.Numeric `json:"nonce"`
}

func (q *Queries) SaveTransferRequest(ctx context.Context, arg SaveTransferRequestParams) error {
	_, err := q.db.Exec(ctx, saveTransferRequest,
		arg.Address,
		arg.Signature,
		arg.ChainID,
		arg.DestinationChain,
		arg.DestinationAddress,
		arg.Symbol,
		arg.Amount,
		arg.Nonce,
	)
	return err
}
