// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: utxo_reservations.sql

package sqlc

import (
	"context"
)

const saveUtxoReservations = `-- name: SaveUtxoReservations :exec
INSERT INTO utxo_reservations (utxo_tx_id, utxo_vout, reservation_id)
VALUES (unnest($1::bytea[]), unnest($2::bigint[]), unnest($3::bigint[]))
`

type SaveUtxoReservationsParams struct {
	Column1 [][]byte `json:"column_1"`
	Column2 []int64  `json:"column_2"`
	Column3 []int64  `json:"column_3"`
}

func (q *Queries) SaveUtxoReservations(ctx context.Context, arg SaveUtxoReservationsParams) error {
	_, err := q.db.Exec(ctx, saveUtxoReservations, arg.Column1, arg.Column2, arg.Column3)
	return err
}
